services:
  web:
    image: movie-stream-web-dev:1.0.1
    container_name: movie-stream-web-dev
    ports:
      - "5173:5173"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api:
    image: movie-stream-api-dev:1.0.1
    container_name: movie-stream-api-dev
    build:
      context: ./server/movie-stream-api
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - path: ./server/movie-stream-api/go.mod
          action: rebuild
        - path: ./server/movie-stream-api/go.sum
          action: rebuild
        - path: ./server/movie-stream-api
          target: /app
          action: sync